export const movies = [
  {
    title: "The Godfather",
    director: "Francis Ford Coppola",
    genre: "Crime",
    duration: "2h 55min",
    image: "https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg",
    rating: 9.5,
    releaseDate: 1972,
    occasion: "Alone",
    link: "https://www.justwatch.com/us/movie/the-godfather-part-i",
    trailer: "https://www.imdb.com/video/vi1348706585?playlistId=tt0068646",
  },
  {
    title: "The Shawshank Redemption",
    director: "Frank Darabont",
    genre: "Drama",
    duration: "2h 22min",
    image: "https://m.media-amazon.com/images/I/51NiGlapXlL._AC_.jpg",
    rating: 9.3,
    releaseDate: 1994,
    occasion: "Date",
    link: "https://www.justwatch.com/us/movie/the-shawshank-redemption",
    trailer: "https://www.imdb.com/video/vi3877612057?playlistId=tt0111161",
  },
  {
    title: "The Dark Knight",
    director: "Christopher Nolan",
    genre: "Action",
    duration: "2h 32min",
    image: "https://m.media-amazon.com/images/I/91KkWf50SoL._SL1500_.jpg",
    rating: 9.0,
    releaseDate: 2008,
    occasion: "Friends",
    link: "https://www.justwatch.com/us/movie/batman-the-dark-knight",
    trailer: "https://www.imdb.com/video/vi324468761?playlistId=tt0468569",
  },
  {
    title: "Schindler's List",
    director: "Christopher Nolan",
    genre: "History",
    duration: "3h 15min",
    image: "https://m.media-amazon.com/images/M/MV5BNDE4OTMxMTctNmRhYy00NWE2LTg3YzItYTk3M2UwOTU5Njg4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg",
    rating: 8.9,
    releaseDate: 1993,
    occasion: "Family",
    link: "https://www.justwatch.com/us/movie/schindlers-list",
    trailer: "https://www.imdb.com/video/vi1158527769?playlistId=tt0108052",
  },
  {
    title: "No Time to Die",
    director: "Cary Joji Fukunaga",
    genre: "Action",
    duration: "2h 43min",
    image: "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/no-time-to-die-poster-1570438717.jpg",
    rating: 7.6,
    releaseDate: 2021,
    occasion: "Date",
    link: "https://www.justwatch.com/us/movie/no-time-to-die-2020",
    trailer: "https://www.imdb.com/video/vi3903767321?playlistId=tt2382320",
  },
  {
    title: "Dune",
    director: "Denis Villeneuve",
    genre: "Adventure",
    duration: "2h 35min",
    image: "https://pics.filmaffinity.com/Dune-367914309-large.jpg",
    rating: 8.3,
    releaseDate: 2021,
    occasion: "Date",
    link: "https://www.justwatch.com/us/movie/dune-2021",
    trailer: "https://www.imdb.com/video/vi3986080537?playlistId=tt1160419",
  },
  {
    title: "Halloween Kills",
    director: "David Gordon Green",
    genre: "Slasher",
    duration: "1h 45min",
    image: "https://pics.filmaffinity.com/Halloween_Kills-155251220-large.jpg",
    rating: 6.1,
    releaseDate: 2021,
    occasion: "Friends",
    link: "https://www.justwatch.com/us/movie/halloween-kills",
    trailer: "https://www.imdb.com/video/vi2091041561?playlistId=tt10665338",
  },
  {
    title: "The Black Phone",
    director: "Scott Derrickson",
    genre: "Horror",
    duration: "1h 42min",
    image: "https://i1.wp.com/www.socialnews.xyz/wp-content/uploads/2021/10/14/the-black-phone-movie-HD-poster-.jpg?quality=80&zoom=1&ssl=1",
    rating: 9.0,
    releaseDate: 2021,
    occasion: "Date",
    link: "https://www.justwatch.com/us/movie/the-black-phone",
    trailer: "https://www.imdb.com/video/vi3684549401?playlistId=tt7144666",
  },
  {
    title: "Shang-Chi and the Legend of the Ten Rings",
    director: "Destin Daniel Cretton",
    genre: "Fantasy",
    duration: "2h 12min",
    image: "https://m.media-amazon.com/images/M/MV5BNTliYjlkNDQtMjFlNS00NjgzLWFmMWEtYmM2Mzc2Zjg3ZjEyXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_FMjpg_UX1000_.jpg",
    rating: 7.9,
    releaseDate: 2021,
    occasion: "Friends",
    link: "https://www.justwatch.com/us/movie/shang-chi-and-the-legend-of-the-ten-rings",
    trailer: "https://www.imdb.com/video/vi558809113?playlistId=tt9376612",
  },
  {
    title: "Hocus Pocus",
    director: "Kenny Ortega",
    genre: "Comedy",
    duration: "1h 36min",
    image: "https://m.media-amazon.com/images/I/81jh4R-eihL._SL1500_.jpg",
    rating: 6.9,
    releaseDate: 1993,
    occasion: "Family",
    link: "https://www.justwatch.com/us/movie/hocus-pocus",
    trailer: "https://www.imdb.com/video/vi1763031833?playlistId=tt0107120",
  },
  {
    title: "Scream",
    director: "Wes Craven",
    genre: "Horror",
    duration: "1h 51min",
    image: "https://pics.filmaffinity.com/Scream_Vigila_qui_n_llama-786162434-large.jpg",
    rating: 7.3,
    releaseDate: 1996,
    occasion: "Date",
    link: "https://www.justwatch.com/us/movie/scream-1",
    trailer: "https://www.imdb.com/video/vi1175821337?playlistId=tt0117571",
  },
  {
    title: "Cruella",
    director: "Craig Gillespie",
    genre: "Adventure",
    duration: "2h 14min",
    image: "https://es.web.img3.acsta.net/pictures/21/04/21/11/08/5393301.jpg",
    rating: 7.4,
    releaseDate: 2021,
    occasion: "Date",
    link: "https://www.justwatch.com/us/movie/cruella",
    trailer: "https://www.imdb.com/video/vi1608499225?playlistId=tt3228774",
  },
  {
    title: "Knives Out",
    director: "Rian Johnson",
    genre: "Crime",
    duration: "2h 10min",
    image: "https://m.media-amazon.com/images/M/MV5BMGUwZjliMTAtNzAxZi00MWNiLWE2NzgtZGUxMGQxZjhhNDRiXkEyXkFqcGdeQXVyNjU1NzU3MzE@._V1_.jpg",
    rating: 7.9,
    releaseDate: 2019,
    occasion: "Alone",
    link: "https://www.justwatch.com/us/movie/knives-out",
    trailer: "https://www.imdb.com/video/vi2464857881?playlistId=tt8946378",
  },
  {
    title: "Parasite",
    director: "Bong Joon Ho",
    genre: "Thriller",
    duration: "2h 12min",
    image: "https://m.media-amazon.com/images/M/MV5BYWZjMjk3ZTItODQ2ZC00NTY5LWE0ZDYtZTI3MjcwN2Q5NTVkXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_.jpg",
    rating: 8.6,
    releaseDate: 2019,
    occasion: "Family",
    link: "https://www.justwatch.com/us/movie/parasite-2019",
    trailer: "https://www.imdb.com/video/vi1015463705?playlistId=tt6751668",
  },
  {
    title: "Titanic",
    director: "James Cameron",
    genre: "Romance",
    duration: "3h 14min",
    image: "https://m.media-amazon.com/images/M/MV5BMDdmZGU3NDQtY2E5My00ZTliLWIzOTUtMTY4ZGI1YjdiNjk3XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_.jpg",
    rating: 7.8,
    releaseDate: 1997,
    occasion: "Date",
    link: "https://www.justwatch.com/us/movie/titanic-1997",
    trailer: "https://www.imdb.com/video/vi907189785?playlistId=tt0120338",
  },
  {
    title: "Midsommar",
    director: "Ari Aster",
    genre: "Drama",
    duration: "2h 28min",
    image: "https://pics.filmaffinity.com/Midsommar-578791309-large.jpg",
    rating: 7.1,
    releaseDate: 2019,
    occasion: "Alone",
    link: "https://www.justwatch.com/us/movie/midsommar",
    trailer: "https://www.imdb.com/video/vi1256832025?playlistId=tt8772262",
  },
  {
    title: "Heat",
    director: "Michael Mann",
    genre: "Crime",
    duration: "2h 50min",
    image: "https://deepfocusreview.com/wp-content/uploads/2016/12/heat.jpg",
    rating: 8.2,
    releaseDate: 1995,
    occasion: "Alone",
    link: "https://www.justwatch.com/us/movie/heat-1995",
    trailer: "https://www.imdb.com/video/vi664516889?playlistId=tt0113277",
  },
  {
    title: "Friday the 13th",
    director: "Sean S. Cunningham",
    genre: "Slasher",
    duration: "1h 35min",
    image: "https://m.media-amazon.com/images/I/61MbE1AFheL._AC_SY879_.jpg",
    rating: 6.4,
    releaseDate: 1980,
    occasion: "Date",
    link: "https://www.justwatch.com/us/movie/friday-the-13th-1980",
    trailer: "https://www.imdb.com/video/vi3229400601?playlistId=tt0080761",
  },
  {
    title: "Joker",
    director: "Todd Phillips",
    genre: "Drama",
    duration: "2h 2min",
    image: "https://cdn11.bigcommerce.com/s-ydriczk/images/stencil/1280x1280/products/89058/93685/Joker-2019-Final-Style-steps-Poster-buy-original-movie-posters-at-starstills__62518.1572351179.jpg?c=2",
    rating: 8.4,
    releaseDate: 2019,
    occasion: "Friends",
    link: "https://www.justwatch.com/us/movie/joker-2019",
    trailer: "https://www.imdb.com/video/vi1723318041?playlistId=tt7286456",
  },
  {
    title: "Once Upon a Time... in Hollywoodname",
    director: "Quentin Tarantino",
    genre: "Comedy",
    duration: "2h 42min",
    image: "https://m.media-amazon.com/images/I/71SrtFM0lSL._AC_SY679_.jpg",
    rating: 7.6,
    releaseDate: 2019,
    occasion: "Alone",
    link: "https://www.justwatch.com/us/movie/once-upon-a-time-in-hollywood",
    trailer: "https://www.imdb.com/video/vi1385741849?playlistId=tt7131622",
  },
  {
    title: "Blade Runner 2049",
    director: "Denis Villeneuve",
    genre: "Action",
    duration: "2h 44min",
    image: "https://m.media-amazon.com/images/I/61MCwtM0LaL._AC_.jpg",
    rating: 8.0,
    releaseDate: 2017,
    occasion: "Friends",
    link: "https://www.justwatch.com/us/movie/blade-runner-2049",
    trailer: "https://www.imdb.com/video/vi3362371865?playlistId=tt1856101",
  },
  {
    title: "The Nightmare Before Christmas",
    director: "Henry Selick",
    genre: "Animation",
    duration: "1h 16min",
    image: "https://m.media-amazon.com/images/M/MV5BNWE4OTNiM2ItMjY4Ni00ZTViLWFiZmEtZGEyNGY2ZmNlMzIyXkEyXkFqcGdeQXVyMDU5NDcxNw@@._V1_FMjpg_UX1000_.jpg",
    rating: 8.0,
    releaseDate: 1993,
    occasion: "Family",
    link: "https://www.justwatch.com/us/movie/the-nightmare-before-christmas",
    trailer: "https://www.imdb.com/video/vi1628814105?playlistId=tt0107688",
  },
  {
    title: "The Shining",
    director: "Stanley Kubrick",
    genre: "Horror",
    duration: "2h 26min",
    image: "https://m.media-amazon.com/images/I/51f4xOLpVTL._AC_.jpg",
    rating: 8.4,
    releaseDate: 1980,
    occasion: "Date",
    link: "https://www.justwatch.com/us/movie/the-shining",
    trailer: "https://www.imdb.com/video/vi2689121305?playlistId=tt0081505",
  },
  {
    title: "Harry Potter and the Sorcerer's Stone",
    director: "director",
    genre: "Fantasy",
    duration: "2h 32min",
    image: "https://m.media-amazon.com/images/I/715YKSv-XuL._AC_SY679_.jpg",
    rating: 7.6,
    releaseDate: 2001,
    occasion: "Family",
    link: "https://www.justwatch.com/us/movie/harry-potter-and-the-philosophers-stone",
    trailer: "https://www.imdb.com/video/vi3115057433?playlistId=tt0241527",
  },
  {
    title: "The Wolf of Wall Street",
    director: "Martin Scorsese",
    genre: "Biography",
    duration: "3h 0min",
    image: "https://pics.filmaffinity.com/El_lobo_de_Wall_Street-333927390-large.jpg",
    rating: 8.2,
    releaseDate: 2013,
    occasion: "Friends",
    link: "https://www.justwatch.com/us/movie/wolf-of-wall-street-the",
    trailer: "https://www.imdb.com/video/vi2312218649?playlistId=tt0993846",
  },
  {
    title: "Fight Club",
    director: "David Fincher",
    genre: "Drama",
    duration: "2h 19min",
    image: "https://m.media-amazon.com/images/M/MV5BMmEzNTkxYjQtZTc0MC00YTVjLTg5ZTEtZWMwOWVlYzY0NWIwXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg",
    rating: 8.8,
    releaseDate: 1999,
    occasion: "Alone",
    link: "https://www.justwatch.com/us/movie/fight-club",
    trailer: "https://www.imdb.com/video/vi781228825?playlistId=tt0137523",
  },
  {
    title: "Beetle Juice",
    director: "Tim Burton",
    genre: "Comedy",
    duration: "1h 32min",
    image: "https://m.media-amazon.com/images/I/51SS7iFY3KL._AC_.jpg",
    rating: 7.5,
    releaseDate: 1988,
    occasion: "Family",
    link: "https://www.justwatch.com/us/movie/beetlejuice",
    trailer: "https://www.imdb.com/video/vi4170302233?playlistId=tt0094721",
  },
  {
    title: "The Matrix",
    director: "Lana & Lilly Wachowski",
    genre: "Action",
    duration: "2h 16min",
    image: "https://m.media-amazon.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg",
    rating: 8.7,
    releaseDate: 1999,
    occasion: "Alone",
    link: "https://www.justwatch.com/us/movie/the-matrix",
    trailer: "https://www.imdb.com/video/vi1032782617?playlistId=tt0133093",
  },
  {
    title: "It",
    director: "Andy Muschietti",
    genre: "Horror",
    duration: "2h 15min",
    image: "https://m.media-amazon.com/images/I/61LokfYMGnL._AC_SY679_.jpg",
    rating: 7.3,
    releaseDate: 2017,
    occasion: "Date",
    link: "https://www.justwatch.com/us/movie/it-2017",
    trailer: "https://www.imdb.com/video/vi1396095257?playlistId=tt1396484",
  },
  {
    title: "Interestelar",
    director: "Christopher Nolan",
    genre: "Science Fiction",
    duration: "2h 49min",
    image: "https://m.media-amazon.com/images/I/716P1xCmnPL._AC_SY741_.jpg",
    rating: 8.6,
    releaseDate: 2014,
    occasion: "Alone",
    link: "https://www.justwatch.com/us/movie/interstellar",
    trailer: "https://www.imdb.com/video/vi1586278169?playlistId=tt0816692",
  },
  {
    title: "The Godfather: Part II",
    director: "Francis Ford Coppola",
    genre: "Crime",
    duration: "3h 22min",
    image: "https://m.media-amazon.com/images/M/MV5BMWMwMGQzZTItY2JlNC00OWZiLWIyMDctNDk2ZDQ2YjRjMWQ0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg",
    rating: 9.0,
    releaseDate: 1974,
    occasion: "Alone",
    link: "https://www.justwatch.com/us/movie/the-godfather-part-ii",
    trailer: "https://www.imdb.com/video/vi696162841?playlistId=tt0071562",
  },
  {
    title: "12 Angry Men",
    director: "director",
    genre: "Crime",
    duration: "1h 36min",
    image: "https://m.media-amazon.com/images/I/81LX+JlavLL._AC_SY741_.jpg",
    rating: 9.0,
    releaseDate: 1957,
    occasion: "Alone",
    link: "https://www.justwatch.com/us/movie/12-angry-men",
    trailer: "https://www.imdb.com/video/vi3452609817?playlistId=tt0050083",
  },
  {
    title: "The Lord of the Rings: The Return of the King",
    director: "Peter Jackson",
    genre: "Adventure",
    duration: "3h 21min",
    image: "https://cdn.shopify.com/s/files/1/0057/3728/3618/products/c468809972e1fb4b7b0c56b07db68987_a25dc22c-c83a-479d-a241-10fa55e7b36b_480x.progressive.jpg?v=1573588780",
    rating: 8.9,
    releaseDate: 2003,
    occasion: "Alone",
    link: "https://www.justwatch.com/us/movie/the-return-of-the-king",
    trailer: "https://www.imdb.com/video/vi2073101337?playlistId=tt0167260",
  },
  {
    title: "Pulp Fiction",
    director: "Quentin Tarantino",
    genre: "Crime",
    duration: "2h 34min",
    image: "https://m.media-amazon.com/images/I/91Zi3y-GRDL._AC_SY741_.jpg",
    rating: 8.9,
    releaseDate: 1994,
    occasion: "Friends",
    link: "https://www.justwatch.com/us/movie/pulp-fiction",
    trailer: "https://www.imdb.com/video/vi2620371481?playlistId=tt0110912",
  },
  {
    title: "The Good, The Bad And The Ugly",
    director: "Sergio Leone",
    genre: "Western",
    duration: "2h 41min",
    image: "https://m.media-amazon.com/images/I/71mpYhyGQSL._AC_SY741_.jpg",
    rating: 8.8,
    releaseDate: 1966,
    occasion: "Alone",
    link: "https://www.justwatch.com/us/movie/man-with-no-name-3-the-good-the-bad-and-the-ugly",
    trailer: "https://www.imdb.com/video/vi3416964889?playlistId=tt0060196",
  },
  {
    title: "The Lord of the Rings: The Fellowship of the Ring",
    director: "Peter Jackson",
    genre: "Adventure",
    duration: "2h 58min",
    image: "https://m.media-amazon.com/images/I/81EBp0vOZZL._AC_SY741_.jpg",
    rating: 8.8,
    releaseDate: 2001,
    occasion: "Alone",
    link: "https://www.justwatch.com/us/movie/lord-of-the-rings-i-the-fellowship-of-the-ring",
    trailer: "https://www.imdb.com/video/vi2073101337?playlistId=tt0120737",
  },
  {
    title: "Forrest Gump",
    director: "Robert Zemeckis",
    genre: "Drama",
    duration: "2h 22min",
    image: "https://m.media-amazon.com/images/I/61A9gnCrA3L._AC_SX522_.jpg",
    rating: 8.8,
    releaseDate: 1994,
    occasion: "Date",
    link: "https://www.justwatch.com/us/movie/forrest-gump",
    trailer: "https://www.imdb.com/video/vi3567517977?playlistId=tt0109830",
  },
  {
    title: "Inception",
    director: "Christopher Nolan",
    genre: "Science Fiction",
    duration: "2h 28min",
    image: "https://m.media-amazon.com/images/I/51bDICODpZL._AC_.jpg",
    rating: 8.8,
    releaseDate: 2010,
    occasion: "occasion",
    link: "https://www.justwatch.com/us/movie/inception",
    trailer: "https://www.imdb.com/video/vi2959588889?playlistId=tt1375666",
  },
  {
    title: "The Lord of the Rings: The Two Towers",
    director: "Peter Jackson",
    genre: "Adventure",
    duration: "2h 59min",
    image: "https://m.media-amazon.com/images/I/81eqQvveI6L._AC_SY679_.jpg",
    rating: 8.7,
    releaseDate: 2001,
    occasion: "Alone",
    link: "https://www.justwatch.com/us/movie/the-lord-of-the-rings-the-two-towers",
    trailer: "https://www.imdb.com/video/vi2073101337?playlistId=tt0167261",
  },
  {
    title: "Star Wars: Episode V - The Empire Strikes Back",
    director: "Irvin Kershner",
    genre: "Science Fiction",
    duration: "2h 4min",
    image: "https://m.media-amazon.com/images/M/MV5BYmU1NDRjNDgtMzhiMi00NjZmLTg5NGItZDNiZjU5NTU4OTE0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg",
    rating: 8.7,
    releaseDate: 1980,
    occasion: "Alone",
    link: "https://www.justwatch.com/us/movie/star-wars-episode-v-the-empire-strikes-back",
    trailer: "https://www.imdb.com/video/vi221753881?playlistId=tt0080684",
  },
  {
    title: "Goodfellas",
    director: "Martin Scorsese",
    genre: "Crime",
    duration: "2h 026in",
    image: "https://m.media-amazon.com/images/I/61Ot42kXQsL._AC_SY741_.jpg",
    rating: 8.7,
    releaseDate: 1990,
    occasion: "Alone",
    link: "https://www.justwatch.com/us/movie/goodfellas",
    trailer: "https://www.imdb.com/video/vi2673654553?playlistId=tt0099685",
  },
  {
    title: "One Flew Over the Cuckoo's Nest",
    director: "Milos Forman",
    genre: "Drama",
    duration: "2h 13min",
    image: "https://m.media-amazon.com/images/I/51YcJ1oo2QL._AC_.jpg",
    rating: 8.7,
    releaseDate: 1975,
    occasion: "Date",
    link: "https://www.justwatch.com/us/movie/one-flew-over-the-cuckoos-nest",
    trailer: "https://www.imdb.com/video/vi3943282969?playlistId=tt0073486",
  },
  {
    title: "The Silence of the Lambs",
    director: "Jonathan Demme",
    genre: "Thriller",
    duration: "1h 58min",
    image: "https://m.media-amazon.com/images/I/41dJipyydvL._AC_.jpg",
    rating: 8.6,
    releaseDate: 1991,
    occasion: "Date",
    link: "https://www.justwatch.com/us/movie/the-silence-of-the-lambs",
    trailer: "https://www.imdb.com/video/vi3377380121?playlistId=tt0102926",
  },
  {
    title: "Se7en",
    director: "David Fincher",
    genre: "Crime",
    duration: "2h 7min",
    image: "https://m.media-amazon.com/images/M/MV5BOTUwODM5MTctZjczMi00OTk4LTg3NWUtNmVhMTAzNTNjYjcyXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg",
    rating: 8.6,
    releaseDate: 1995,
    occasion: "Date",
    link: "https://www.justwatch.com/us/movie/se7en",
    trailer: "https://www.imdb.com/video/vi2508831257?playlistId=tt0114369",
  },
  {
    title: "Star Wars",
    director: "George Lucas",
    genre: "Science Fiction",
    duration: "2h 1min",
    image: "https://m.media-amazon.com/images/I/A1wnJQFI82L._AC_SY879_.jpg",
    rating: 8.6,
    releaseDate: 1977,
    occasion: "Alone",
    link: "https://www.justwatch.com/us/movie/star-wars-episode-iv-a-new-hope",
    trailer: "https://www.imdb.com/video/vi1317709849?playlistId=tt0076759",
  },
  {
    title: "Saving Private Ryan",
    director: "Steven Spielberg",
    genre: "War",
    duration: "2h 49min",
    image: "https://m.media-amazon.com/images/I/716Pp2nRvzL._AC_SY679_.jpg",
    rating: 8.6,
    releaseDate: 1998,
    occasion: "Alone",
    link: "https://www.justwatch.com/us/movie/saving-private-ryan",
    trailer: "https://www.imdb.com/video/vi1701906201?playlistId=tt0120815",
  },
  {
    title: "Spirited Away",
    director: "Hayao Miyazaki",
    genre: "Animation",
    duration: "2h 5min",
    image: "https://m.media-amazon.com/images/I/412B0Cvv2GL._AC_.jpg",
    rating: 8.6,
    releaseDate: 2001,
    occasion: "Family",
    link: "https://www.justwatch.com/us/movie/spirited-away",
    trailer: "https://www.imdb.com/video/vi3619684633?playlistId=tt0245429",
  },
  {
    title: "The Green Mile",
    director: "Frank Darabont",
    genre: "Drama",
    duration: "3h 9min",
    image: "https://m.media-amazon.com/images/I/51mvJdnlXrL._AC_.jpg",
    rating: 8.6,
    releaseDate: 1999,
    occasion: "Date",
    link: "https://www.justwatch.com/us/movie/green-mile-the",
    trailer: "https://www.imdb.com/video/vi552796441?playlistId=tt0120689",
  },
  {
    title: "Léon",
    director: "Luc Besson",
    genre: "Action",
    duration: "1h 50min",
    image: "https://m.media-amazon.com/images/I/71ezOtH+z5L._AC_SY679_.jpg",
    rating: 8.5,
    releaseDate: 1994,
    occasion: "Date",
    link: "https://www.justwatch.com/us/movie/leon-the-professional",
    trailer: "https://www.imdb.com/video/vi2744254745?playlistId=tt0110413",
  },
  {
    title: "The Pianist",
    director: "Roman Polanski",
    genre: "Biography",
    duration: "2h 30min",
    image: "https://m.media-amazon.com/images/M/MV5BOWRiZDIxZjktMTA1NC00MDQ2LWEzMjUtMTliZmY3NjQ3ODJiXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_FMjpg_UX1000_.jpg",
    rating: 8.5,
    releaseDate: 2002,
    occasion: "Family",
    link: "https://www.justwatch.com/us/movie/the-pianist",
    trailer: "https://www.imdb.com/video/vi988938521?playlistId=tt0253474",
  },
  {
    title: "Terminator 2: Judgment Day",
    director: "James Cameron",
    genre: "Science Fiction",
    duration: "2h 17min",
    image: "https://m.media-amazon.com/images/M/MV5BMGU2NzRmZjUtOGUxYS00ZjdjLWEwZWItY2NlM2JhNjkxNTFmXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg",
    rating: 8.5,
    releaseDate: 1991,
    occasion: "Friends",
    link: "https://www.justwatch.com/us/movie/terminator-2-judgment-day",
    trailer: "https://www.imdb.com/video/vi2748889369?playlistId=tt0103064",
  },
  {
    title: "The Usual Suspects",
    director: "Bryan Singer",
    genre: "Crime",
    duration: "1h 46min",
    image: "https://m.media-amazon.com/images/I/51ANy73yJuL._AC_.jpg",
    rating: 8.5,
    releaseDate: 1995,
    occasion: "Alone",
    link: "https://www.justwatch.com/us/movie/usual-suspects-the",
    trailer: "https://www.imdb.com/video/vi2717188377?playlistId=tt0114814",
  },
  {
    title: "Back to the Future",
    director: "Robert Zemeckis",
    genre: "Science Fiction",
    duration: "1h 56min",
    image: "https://m.media-amazon.com/images/I/51VLaiKIRHL._AC_.jpg",
    rating: 8.5,
    releaseDate: 1985,
    occasion: "Family",
    link: "https://www.justwatch.com/us/movie/back-to-the-future-part-i",
    trailer: "https://www.imdb.com/video/vi252380953?playlistId=tt0088763",
  },
  {
    title: "Psycho",
    director: "Alfred Hitchcock",
    genre: "Horror",
    duration: "1h 49min",
    image: "https://m.media-amazon.com/images/I/81iY9eRSOcL._AC_SY679_.jpg",
    rating: 8.5,
    releaseDate: 1960,
    occasion: "Date",
    link: "https://www.justwatch.com/us/movie/psycho",
    trailer: "https://www.imdb.com/video/vi607099161?playlistId=tt0054215",
  },
  {
    title: "The Lion King",
    director: "Roger Allers & Rob Minkoff",
    genre: "Animation",
    duration: "1h 28min",
    image: "https://m.media-amazon.com/images/I/51-2ekSfwBL._AC_UY445_.jpg",
    rating: 8.5,
    releaseDate: 1994,
    occasion: "Family",
    link: "https://www.justwatch.com/us/movie/the-lion-king",
    trailer: "https://www.imdb.com/video/vi3764362265?playlistId=tt0110357",
  },
  {
    title: "Whiplash",
    director: "Damien Chazelle",
    genre: "Drama",
    duration: "1h 46min",
    image: "https://m.media-amazon.com/images/I/51GXgsoSPaL._AC_.jpg",
    rating: 8.5,
    releaseDate: 2014,
    occasion: "Alone",
    link: "https://www.justwatch.com/us/movie/whiplash",
    trailer: "https://www.imdb.com/video/vi4006456345?playlistId=tt2582802",
  },
  {
    title: "Gladiator",
    director: "Ridley Scott",
    genre: "Action",
    duration: "2h 35min",
    image: "https://m.media-amazon.com/images/I/71sj8Yt20qL._AC_SY679_.jpg",
    rating: 8.5,
    releaseDate: 2000,
    occasion: "Alone",
    link: "https://www.justwatch.com/us/movie/gladiator-2000",
    trailer: "https://www.imdb.com/video/vi2628367897?playlistId=tt0172495",
  },
  {
    title: "The Departed",
    director: "Martin Scorsese",
    genre: "Crime",
    duration: "2h 31min",
    image: "https://m.media-amazon.com/images/I/51cjgP9KO7L._AC_.jpg",
    rating: 8.5,
    releaseDate: 2006,
    occasion: "Date",
    link: "https://www.justwatch.com/us/movie/the-departed",
    trailer: "https://www.imdb.com/video/vi2760573209?playlistId=tt0407887",
  },
  {
    title: "Intouchables",
    director: "Olivier Nakache",
    genre: "Biography",
    duration: "1h 52min",
    image: "https://m.media-amazon.com/images/I/51WbHjvEceL._AC_.jpg",
    rating: 8.5,
    releaseDate: 2011,
    occasion: "Family",
    link: "https://www.justwatch.com/us/movie/the-intouchables",
    trailer: "https://www.imdb.com/video/vi59285529?playlistId=tt1675434",
  },
  {
    title: "The Prestige",
    director: "Christopher Nolan",
    genre: "Mystery",
    duration: "2h 10min",
    image: "https://m.media-amazon.com/images/I/41ra5qmuynL._AC_.jpg",
    rating: 8.5,
    releaseDate: 2006,
    occasion: "Date",
    link: "https://www.justwatch.com/us/movie/the-prestige",
    trailer: "https://www.imdb.com/video/vi2885334553?playlistId=tt0482571",
  },
  {
    title: "Alien",
    director: "Ridley Scott",
    genre: "Science Fiction",
    duration: "1h 57min",
    image: "https://m.media-amazon.com/images/I/41ltBoq45nL._AC_.jpg",
    rating: 8.4,
    releaseDate: 1979,
    occasion: "Friends",
    link: "https://www.justwatch.com/us/movie/alien",
    trailer: "https://www.imdb.com/video/vi1497801241?playlistId=tt0078748",
  },
  {
    title: "Apocalypse Now",
    director: "Francis Ford Coppola",
    genre: "War",
    duration: "2h 27min",
    image: "https://m.media-amazon.com/images/I/71SawqPnYFL._AC_SY550_.jpg",
    rating: 8.4,
    releaseDate: 1979,
    occasion: "Alone",
    link: "https://www.justwatch.com/us/movie/apocalypse-now-redux",
    trailer: "https://www.imdb.com/video/vi3543773721?playlistId=tt0078788",
  },
  {
    title: "Memento",
    director: "Christopher Nolan",
    genre: "Mystery",
    duration: "1h 53min",
    image: "https://m.media-amazon.com/images/I/51jojzqpkPL._AC_.jpg",
    rating: 8.4,
    releaseDate: 2000,
    occasion: "Date",
    link: "https://www.justwatch.com/us/movie/memento",
    trailer: "https://www.imdb.com/video/vi3220356889?playlistId=tt0209144",
  },
  {
    title: "Raiders of the Lost Ark",
    director: "Steven Spielberg",
    genre: "Adventure",
    duration: "1h 55min",
    image: "https://m.media-amazon.com/images/I/81UOBSDQh0L._AC_SL1500_.jpg",
    rating: 8.4,
    releaseDate: 1981,
    occasion: "Date",
    link: "https://www.justwatch.com/us/movie/indiana-jones-and-the-raiders-of-the-lost-ark",
    trailer: "https://www.imdb.com/video/vi3747396377?playlistId=tt0082971",
  },
  {
    title: "Django Unchained",
    director: "Quentin Tarantino",
    genre: "Western",
    duration: "2h 45min",
    image: "https://m.media-amazon.com/images/I/51cBoriNk5L._AC_.jpg",
    rating: 8.4,
    releaseDate: 2012,
    occasion: "Alone",
    link: "https://www.justwatch.com/us/movie/django-unchained",
    trailer: "https://www.imdb.com/video/vi2291574553?playlistId=tt1853728",
  },
  {
    title: "Paths of Glory",
    director: "Stanley Kubrick",
    genre: "War",
    duration: "1h 28min",
    image: "https://m.media-amazon.com/images/M/MV5BNjViMmRkOTEtM2ViOS00ODg0LWJhYWEtNTBlOGQxNDczOGY3XkEyXkFqcGdeQXVyMDI2NDg0NQ@@._V1_.jpg",
    rating: 8.4,
    releaseDate: 1957,
    occasion: "Alone",
    link: "https://www.justwatch.com/us/movie/paths-of-glory",
    trailer: "https://www.imdb.com/video/vi763627801?playlistId=tt0050825",
  },
  {
    title: "WALL·E",
    director: "Andrew Stanton",
    genre: "Animation",
    duration: "1h 38min",
    image: "https://m.media-amazon.com/images/I/51RoZRgIHtL._AC_.jpg",
    rating: 8.4,
    releaseDate: 2008,
    occasion: "Family",
    link: "https://www.justwatch.com/us/movie/wall-e",
    trailer: "https://www.imdb.com/video/vi2192703769?playlistId=tt0910970",
  },
  {
    title: "Dr. Strangelove",
    director: "Stanley Kubrick",
    genre: "Comedy",
    duration: "1h 35min",
    image: "https://m.media-amazon.com/images/I/51BRAbLj4PL._AC_.jpg",
    rating: 8.4,
    releaseDate: 1964,
    occasion: "Friends",
    link: "https://www.justwatch.com/us/movie/dr-strangelove-or-how-i-learned-to-stop-worrying-and-love-the-bomb",
    trailer: "https://www.imdb.com/video/vi3726294553?playlistId=tt0057012",
  },
  {
    title: "The Dark Knight Rises",
    director: "Christopher Nolan",
    genre: "Action",
    duration: "2h 44min",
    image: "https://m.media-amazon.com/images/M/MV5BMTk4ODQzNDY3Ml5BMl5BanBnXkFtZTcwODA0NTM4Nw@@._V1_FMjpg_UX1000_.jpg",
    rating: 8.4,
    releaseDate: 2013,
    occasion: "Alone",
    link: "https://www.justwatch.com/us/movie/the-dark-knight-rises",
    trailer: "https://www.imdb.com/video/vi144884505?playlistId=tt1345836",
  },
  {
    title: "Once Upon a Time in America",
    director: "Sergio Leone",
    genre: "Crime",
    duration: "3h 49min",
    image: "https://m.media-amazon.com/images/M/MV5BMGFkNWI4MTMtNGQ0OC00MWVmLTk3MTktOGYxN2Y2YWVkZWE2XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg",
    rating: 8.3,
    releaseDate: 1984,
    occasion: "Alone",
    link: "https://www.justwatch.com/us/movie/once-upon-a-time-in-america",
    trailer: "https://www.imdb.com/video/vi2777395225?playlistId=tt0087843",
  },
  {
    title: "Amadeus",
    director: "Milos Forman",
    genre: "Biography",
    duration: "2h 40min",
    image: "https://pics.filmaffinity.com/Amadeus-718368517-large.jpg",
    rating: 8.3,
    releaseDate: 1984,
    occasion: "Family",
    link: "https://www.justwatch.com/us/movie/amadeus",
    trailer: "https://www.imdb.com/video/vi2535496985?playlistId=tt0086879",
  },
  {
    title: "Braveheart",
    director: "Mel Gibson",
    genre: "History",
    duration: "2h 58min",
    image: "https://images-na.ssl-images-amazon.com/images/I/81dqgVudIDL._RI_.jpg",
    rating: 8.3,
    releaseDate: 1995,
    occasion: "Alone",
    link: "https://www.justwatch.com/us/movie/braveheart",
    trailer: "https://www.imdb.com/video/vi2874063641?playlistId=tt0112573",
  },
  {
    title: "Inglourious Basterds",
    director: "Quentin Tarantino",
    genre: "War",
    duration: "2h 33min",
    image: "https://m.media-amazon.com/images/I/61PXdxTJGPL._AC_SY741_.jpg",
    rating: 8.3,
    releaseDate: 2009,
    occasion: "Date",
    link: "https://www.justwatch.com/us/movie/inglorious-basterds",
    trailer: "https://www.imdb.com/video/vi3738173977?playlistId=tt0361748",
  },
  {
    title: "Good Will Hunting",
    director: "Gus Van Sant",
    genre: "Drama",
    duration: "2h 6min",
    image: "https://pics.filmaffinity.com/El_indomable_Will_Hunting-771762251-large.jpg",
    rating: 8.3,
    releaseDate: 1997,
    occasion: "Family",
    link: "https://www.justwatch.com/us/movie/good-will-hunting",
    trailer: "https://www.imdb.com/video/vi1281211929?playlistId=tt0119217",
  },
  {
    title: "Star Wars: Episode VI - Return of the Jedi",
    director: "Richard Marquand",
    genre: "Science Fiction",
    duration: "2h 11min",
    image: "https://images-na.ssl-images-amazon.com/images/I/81g8vEs4ixL.jpg",
    rating: 8.3,
    releaseDate: 1983,
    occasion: "Alone",
    link: "https://www.justwatch.com/us/movie/star-wars-episode-vi-return-of-the-jedi",
    trailer: "https://www.imdb.com/video/vi1702936345?playlistId=tt0086190",
  },
  {
    title: "2001: A Space Odyssey",
    director: "Stanley Kubrick",
    genre: "Science Fiction",
    duration: "2h 29min",
    image: "https://m.media-amazon.com/images/I/41yU9cqLS8L._AC_.jpg",
    rating: 8.3,
    releaseDate: 1968,
    occasion: "Alone",
    link: "https://www.justwatch.com/us/movie/how-the-solar-system-was-won",
    trailer: "https://www.imdb.com/video/vi2674767897?playlistId=tt0062622",
  },
  {
    title: "Reservoir Dogs",
    director: "Quentin Tarantino",
    genre: "Crime",
    duration: "1h 39min",
    image: "https://m.media-amazon.com/images/M/MV5BZmExNmEwYWItYmQzOS00YjA5LTk2MjktZjEyZDE1Y2QxNjA1XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_FMjpg_UX1000_.jpg",
    rating: 8.3,
    releaseDate: 1992,
    occasion: "Friends",
    link: "https://www.justwatch.com/us/movie/reservoir-dogs",
    trailer: "https://www.imdb.com/video/vi3028484377?playlistId=tt0105236",
  },
  {
    title: "Requiem for a Dream",
    director: "Darren Aronofsky",
    genre: "Drama",
    duration: "1h 42min",
    image: "https://m.media-amazon.com/images/I/71-b2P2qoeL._SY550_.jpg",
    rating: 8.3,
    releaseDate: 2000,
    occasion: "Date",
    link: "https://www.justwatch.com/us/movie/requiem-for-a-dream",
    trailer: "https://www.imdb.com/video/vi2156069145?playlistId=tt0180093",
  },
  {
    title: "Full Metal Jacket",
    director: "Stanley Kubrick",
    genre: "War",
    duration: "1h 56min",
    image: "https://pics.filmaffinity.com/Full_Metal_Jacket-577943737-large.jpg",
    rating: 8.3,
    releaseDate: 1987,
    occasion: "Alone",
    link: "https://www.justwatch.com/us/movie/la-chaqueta-metalica",
    trailer: "https://www.imdb.com/video/vi3225663513?playlistId=tt0093058",
  },
  {
    title: "Man on Fire",
    director: "Tony Scott",
    genre: "Action",
    duration: "2h 26min",
    image: "https://flxt.tmsimg.com/assets/p34417_p_v13_ai.jpg",
    rating: 7.7,
    releaseDate: 2004,
    occasion: "Date",
    link: "https://www.justwatch.com/us/movie/man-on-fire-2004",
    trailer: "https://www.imdb.com/video/vi815268121?playlistId=tt0328107",
  },
  {
    title: "The Bucket List",
    director: "Rob Reiner",
    genre: "Comedy",
    duration: "1h 37min",
    image: "https://m.media-amazon.com/images/I/814t-PPTKQL._SL1500_.jpg",
    rating: 7.4,
    releaseDate: 2007,
    occasion: "Family",
    link: "https://www.justwatch.com/us/movie/the-bucket-list",
    trailer: "https://www.imdb.com/video/vi3367043353?playlistId=tt0825232",
  },
  {
    title: "Taxi Driver",
    director: "Martin Scorsese",
    genre: "Crime",
    duration: "1h 54min",
    image: "https://m.media-amazon.com/images/M/MV5BM2M1MmVhNDgtNmI0YS00ZDNmLTkyNjctNTJiYTQ2N2NmYzc2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_FMjpg_UX1000_.jpg",
    rating: 8.2,
    releaseDate: 1976,
    occasion: "Date",
    link: "https://www.justwatch.com/us/movie/taxi-driver",
    trailer: "https://www.imdb.com/video/vi474987289?playlistId=tt0075314",
  },
  {
    title: "Scarface",
    director: "Brian De Palma",
    genre: "Crime",
    duration: "2h 50min",
    image: "https://i.pinimg.com/originals/bc/f3/fe/bcf3fef7fff3957f2fb582402460e1e4.jpg",
    rating: 8.3,
    releaseDate: 1983,
    occasion: "Alone",
    link: "https://www.justwatch.com/us/movie/scarface-1983",
    trailer: "https://www.imdb.com/video/vi3939802137?playlistId=tt0086250",
  },
  {
    title: "1917",
    director: "Sam Mendes",
    genre: "War",
    duration: "1h 59min",
    image: "https://m.media-amazon.com/images/M/MV5BOTdmNTFjNDEtNzg0My00ZjkxLTg1ZDAtZTdkMDc2ZmFiNWQ1XkEyXkFqcGdeQXVyNTAzNzgwNTg@._V1_.jpg",
    rating: 8.3,
    releaseDate: 2019,
    occasion: "Date",
    link: "https://www.justwatch.com/us/movie/1917",
    trailer: "https://www.imdb.com/video/vi4095655705?playlistId=tt8579674",
  },
  {
    title: "Indiana Jones and the Last Crusade",
    director: "Steven Spielberg",
    genre: "Adventure",
    duration: "2h 7min",
    image: "https://m.media-amazon.com/images/M/MV5BMjNkMzc2N2QtNjVlNS00ZTk5LTg0MTgtODY2MDAwNTMwZjBjXkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_UY1200_CR92,0,630,1200_AL_.jpg",
    rating: 8.2,
    releaseDate: 1989,
    occasion: "Alone",
    link: "https://www.justwatch.com/us/movie/indiana-jones-3",
    trailer: "https://www.imdb.com/video/vi2007669529?playlistId=tt0097576",
  },
  {
    title: "To Kill a Mockingbird",
    director: "Robert Mulligan",
    genre: "Crime",
    duration: "2h 9min",
    image: "https://m.media-amazon.com/images/M/MV5BNmVmYzcwNzMtMWM1NS00MWIyLThlMDEtYzUwZDgzODE1NmE2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg",
    rating: 8.3,
    releaseDate: 1962,
    occasion: "Date",
    link: "https://www.justwatch.com/co/pelicula/matar-a-un-ruisenor",
    trailer: "https://www.imdb.com/video/vi1222941977?playlistId=tt0056592",
  },
  {
    title: "Green Book",
    director: "Peter Farrelly",
    genre: "Biography",
    duration: "2h 10min",
    image: "https://pics.filmaffinity.com/Green_Book-162451488-large.jpg",
    rating: 8.2,
    releaseDate: 2008,
    occasion: "Date",
    link: "https://www.justwatch.com/co/pelicula/green-book",
    trailer: "https://www.imdb.com/video/vi824752921?playlistId=tt6966692",
  },
  {
    title: "The Great Escape",
    director: "John Sturges",
    genre: "History",
    duration: "2h 52min",
    image: "https://m.media-amazon.com/images/M/MV5BNzA2NmYxMWUtNzBlMC00MWM2LTkwNmQtYTFlZjQwODNhOWE0XkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_.jpg",
    rating: 8.2,
    releaseDate: 1963,
    occasion: "Alone",
    link: "https://www.justwatch.com/co/pelicula/la-gran-evasion",
    trailer: "https://www.imdb.com/video/vi1130535193?playlistId=tt0057115",
  },
  {
    title: "No Country for Old Men",
    director: "Ethan Coen",
    genre: "Thriller",
    duration: "2h 2min",
    image: "https://m.media-amazon.com/images/M/MV5BNDMyZDM3ODQtYTBmZC00YzRlLTlkOTEtM2QwNTBhYTJiZTAxXkEyXkFqcGdeQXVyNjI0MTA1MTM@._V1_.jpg",
    rating: 8.1,
    releaseDate: 2007,
    occasion: "Alone",
    link: "https://www.justwatch.com/co/pelicula/no-es-pais-para-viejos",
    trailer: "https://www.imdb.com/video/vi145883417?playlistId=tt0477348",
  },
  {
    title: "The Thing",
    director: "John Carpenter",
    genre: "Horror",
    duration: "1h 49min",
    image: "https://m.media-amazon.com/images/M/MV5BNGViZWZmM2EtNGYzZi00ZDAyLTk3ODMtNzIyZTBjN2Y1NmM1XkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_.jpg",
    rating: 8.1,
    releaseDate: 1982,
    occasion: "Date",
    link: "https://www.justwatch.com/co/pelicula/la-cosa-el-enigma-de-otro-mundo",
    trailer: "https://www.imdb.com/video/vi2298151193?playlistId=tt0084787",
  },
  {
    title: "The Truman Show",
    director: "Peter Weir",
    genre: "Comedy",
    duration: "1h 43min",
    image: "https://pics.filmaffinity.com/El_show_de_Truman_Una_vida_en_directo-130091557-large.jpg",
    rating: 8.1,
    releaseDate: 1998,
    occasion: "Alone",
    link: "https://www.justwatch.com/co/pelicula/el-show-de-truman-una-vida-en-directo",
    trailer: "https://www.imdb.com/video/vi1878327577?playlistId=tt0120382",
  },
  {
    title: "Jurassic Park",
    director: "Steven Spielberg",
    genre: "Adventure",
    duration: "2h 7min",
    image: "https://images-na.ssl-images-amazon.com/images/I/8142L+TQEyL.jpg",
    rating: 8.2,
    releaseDate: 1993,
    occasion: "Alone",
    link: "https://www.justwatch.com/co/pelicula/parque-jurasico",
    trailer: "https://www.imdb.com/video/vi177055257?playlistId=tt0107290",
  },
  {
    title: "V for Vendetta",
    director: "James McTeigue",
    genre: "Drama",
    duration: "2h 12min",
    image: "https://pics.filmaffinity.com/V_de_Vendetta-296729466-large.jpg",
    rating: 8.1,
    releaseDate: 2006,
    occasion: "Date",
    link: "https://www.justwatch.com/co/pelicula/v-de-vendetta",
    trailer: "https://www.imdb.com/video/vi4276093209?playlistId=tt0434409",
  },
  {
    title: "Kill Bill: Vol. 1",
    director: "Quentin Tarantino",
    genre: "Action",
    duration: "1h 51min",
    image: "https://pics.filmaffinity.com/Kill_Bill_Volumen_1-216872360-large.jpg",
    rating: 8.1,
    releaseDate: 2003,
    occasion: "Date",
    link: "https://www.justwatch.com/co/pelicula/kill-bill-volumen-1",
    trailer: "https://www.imdb.com/video/vi3102711321?playlistId=tt0266697",
  },
  {
    title: "Catch Me If You Can",
    director: "Steven Spielberg",
    genre: "Biography",
    duration: "2h 21min",
    image: "https://m.media-amazon.com/images/I/81V+b69u3xL._SL1500_.jpg",
    rating: 8.1,
    releaseDate: 2002,
    occasion: "Date",
    link: "https://www.justwatch.com/co/pelicula/atrapame-si-puedes",
    trailer: "https://www.imdb.com/video/vi1220346137?playlistId=tt0264464",
  },
  {
    title: "Room",
    director: "Lenny Abrahamson",
    genre: "Thriller",
    duration: "1h 58min",
    image: "https://m.media-amazon.com/images/M/MV5BMjE4NzgzNzEwMl5BMl5BanBnXkFtZTgwMTMzMDE0NjE@._V1_.jpg",
    rating: 8.1,
    releaseDate: 2015,
    occasion: "Date",
    link: "https://www.justwatch.com/co/pelicula/la-habitacion",
    trailer: "https://www.imdb.com/video/vi321566745?playlistId=tt3170832",
  },
  {
    title: "Gone Girl",
    director: "David Fincher",
    genre: "Mystery",
    duration: "2h 29min",
    image: "https://m.media-amazon.com/images/M/MV5BMTk0MDQ3MzAzOV5BMl5BanBnXkFtZTgwNzU1NzE3MjE@._V1_.jpg",
    rating: 8.1,
    releaseDate: 2014,
    occasion: "Date",
    link: "https://www.justwatch.com/co/pelicula/perdida",
    trailer: "https://www.imdb.com/video/vi1298770969?playlistId=tt2267998",
  },
  {
    title: "The Big Lebowski",
    director: "Joel Coen",
    genre: "Comedy",
    duration: "1h 57min",
    image: "https://cdn.shopify.com/s/files/1/1057/4964/products/the-big-lebowski-vintage-movie-poster-original-1-sheet-27x41_04bfa31d-2870-44dc-9280-3b6ec874dd03_800x.progressive.jpg?v=1587871632",
    rating: 8.1,
    releaseDate: 1998,
    occasion: "Family",
    link: "https://www.justwatch.com/co/pelicula/el-gran-lebowski",
    trailer: "https://www.imdb.com/video/vi4018733337?playlistId=tt0118715",
  },
  {
    title: "Star Trek",
    director: "J.J. Abrams",
    genre: "Science Fiction",
    duration: "2h 7min",
    image: "https://pics.filmaffinity.com/Star_Trek-815589716-large.jpg",
    rating: 7.9,
    releaseDate: 2009,
    occasion: "Alone",
    link: "https://www.justwatch.com/co/pelicula/star-trek",
    trailer: "https://www.imdb.com/video/vi1761608473?playlistId=tt0796366",
  },
  {
    title: "The Breakfast Club",
    director: "John Hughes",
    genre: "Comedy",
    duration: "1h 37min",
    image: "https://m.media-amazon.com/images/M/MV5BOTM5N2ZmZTMtNjlmOS00YzlkLTk3YjEtNTU1ZmQ5OTdhODZhXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg",
    rating: 7.8,
    releaseDate: 1985,
    occasion: "Alone",
    link: "https://www.justwatch.com/co/pelicula/el-club-de-los-cinco",
    trailer: "https://www.imdb.com/video/vi2071703065?playlistId=tt0088847",
  },
];
  

